spring:  
  datasource:
    url: jdbc:mysql://db:3306/healthcare?createDatabaseIfNotExist=true&autoReconnect=true
    username: root
    password: Test@1234
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
