spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/healthcare
    username: root
    password: Test@1234
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoints:
    web:
      exposure:
        include: '*'
