server:
  port: 8080
elasticsearch:
  clustername: ideas2it
  host: localhost
  port: 9300
logging:
  file:
    path: C:/Users/Windows/Documents/Logs/UserLogs/temp
management:
  security:
    enabled: false
spring:
  kafka:
    bootstrap-servers: http://localhost:9092
  cloud:
    stream:
      kafka:
        binder:
          autoAddPartitions: true
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
endpoints:
  spring:
    cloud:
      bus:
        refresh:
          enabled: true
      env:
        enabled: true
