server:
  port: 8080
elasticsearch:
  clustername: ideas2it
  host: localhost
  port: 9300
logging:
  file:
    path: C:/Users/Windows/Documents/Logs/UserLogs/temps
management:
  security:
    enabled: false
spring:
  cloud:
    bus:
      refresh:
        enabled: true
      env:
        enabled: true
endpoints:
  spring:
    cloud:
      bus:
        refresh:
          enabled: true
      env:
        enabled: true
message:
  default:
    name: Subash S...
